// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiWpfExample.WebApi.Data;

namespace WebApiWpfExample.WebApi.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApiWpfExample.WebApi.Data.Model.WeatherObservation", b =>
                {
                    b.Property<int>("WeatherObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("WeatherObservationId");

                    b.ToTable("WeatherObservations");

                    b.HasData(
                        new
                        {
                            WeatherObservationId = 1,
                            Date = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Freezing",
                            TemperatureC = -5
                        },
                        new
                        {
                            WeatherObservationId = 2,
                            Date = new DateTime(2020, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Cool",
                            TemperatureC = 7
                        },
                        new
                        {
                            WeatherObservationId = 3,
                            Date = new DateTime(2020, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Warm",
                            TemperatureC = 15
                        },
                        new
                        {
                            WeatherObservationId = 4,
                            Date = new DateTime(2020, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Hot",
                            TemperatureC = 23
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
